name: Clippy

on:
  push:
    branches:
      - 'master'
  pull_request:

jobs:
  clippy:
    name: ${{ runner.os }}
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          components: clippy
          override: true
          profile: minimal
          toolchain: 1.32.0

      - name: Run Clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --features 'guid serde slog std v1 v3 v4 v5' -- -D warnings
        if: runner.os == 'Windows'

      - name: Run Clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --features 'serde slog std v1 v3 v4 v5' -- -D warnings
        if: runner.os == 'macOS' || runner.os == 'Linux'

    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
