name: Clippy

on:
  push:
    branches:
      - 'master'
  pull_request:

env:
  CLIPPY_WINDOWS_FEATURES: "'guid serde slog std v1 v3 v4 v5'"
  CLIPPY_UNIX_FEATURES: "'serde slog std v1 v3 v4 v5'"

jobs:
  clippy:
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          components: clippy
          override: true
          profile: minimal
          toolchain: 1.32.0

      - name: Run Clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --features $CLIPPY_WINDOWS_FEATURES -- -D warnings
        if: runner.os == 'Windows'

      - name: Run Clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --features $CLIPPY_UNIX_FEATURES -- -D warnings

    strategy:
      matrix:
        os:
          - ubuntu-latest
